### ISSUE TITLE
Horizontal branch isochrone stays in the HR position when in CM mode

### ISSUE THREAD

**Issue by kaleetock** [SkynetRTN/astromancer#19]
I am attaching in image that demonstrates the problem.  Thanks!!
![Screenshot 2024-04-19 at 12 57 42 PM](https://github.com/SkynetRTN/astromancer/assets/47725787/9da26446-38f4-48d2-919f-d8b2fc968d01)

**Comment by RuideFu** [comment]
fixed, pushed to dev and production.
